### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by uutan58** [uutan58/manabi_no_ueki#61]
# 概要

## GItHubProject
https://github.com/users/uutan58/projects/2
***
### MVP
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] マイページ機能
- [ ] プロフィール表示および編集機能
- [ ] カレンダーでのスケジュール管理機能
- [ ] 学習時間の推移グラフで表示
- [ ] 達成率の表示
- [ ] To Do機能
- [ ] バッジ獲得機能
- [ ] Xへのポスト機能
- [ ] Qiitaへの投稿機能
- [ ] 学習時間のレコメンド機能

### 本リリース
- [ ] リマインダー機能
- [ ] ポモドーロタイマー機能
***
## 必要なページ
- [ ] TOP画面（機能紹介）
- [ ] ログイン画面
- [ ] 新規登録画面
- [ ] メールアドレス変更画面
- [ ] パスワード変更画面
- [ ] スケジュール画面（メイン画面）
- [ ] スケジュール管理画面
- [ ] To Do（管理）画面
- [ ] マイページ画面
- [ ] プロフィール画面
- [ ] 学習時間記録画面
- [ ] ゲーミフィケーション管理画面（プロフィール画面に統合も要検討）
- [ ] 記事作成・投稿画面

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---
ゼロベースでissueを拝見してのコメントになります。

■MVP機能とはという観点から
・Xへの投稿
・利用規約
・プライバシー・ポリシー
・メールアドレス変更
・パスワード変更
・ゲーミフィケーション管理画面
・Qiita投稿
・レコメンド機能
・Rumale

上記はMVP機能にしては、やや大きすぎる気がしました。MVPリリース後の実装で良いかと思います。上記をMVPリリース後にすれば、5/15辺りにはMVPリリースができるかと思うので一度スケジュールを見直してみてください。

**Comment by uutan58** [comment]
ご確認ありがとうございます。

私自身、READMEに記述したもののMVPリリース時点での機能が大きいと思っていたため、ご指導いただけて大変有り難いです。
MVPリリース、本リリースまでの実装スケジュールを再調整いたしました。

再度、ご確認の上、ご指導のほどよろしくお願いいたします。
***
# 概要

## GItHubProject
https://github.com/users/uutan58/projects/2
***
## 実装予定の機能
### MVP
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] マイページ機能
- [ ] プロフィール表示および編集機能
- [ ] カレンダーでのスケジュール管理機能
- [ ] 学習時間の推移グラフで表示
- [ ] 達成率の表示
- [ ] To Do機能

### 本リリース
- [ ] リマインダー機能
- [ ] ポモドーロタイマー機能
- [ ] バッジ獲得機能
- [ ] Xへのポスト機能
- [ ] Qiitaへの投稿機能
- [ ] 学習時間のレコメンド機能
- [ ] 利用規約
- [ ] プライバシー・ポリシー
- [ ] メールアドレス変更
- [ ] パスワード変更
- [ ] ゲーミフィケーション関連
***
## 必要なページ
- [ ] TOP画面（機能紹介）
- [ ] ログイン画面
- [ ] 新規登録画面
- [ ] メールアドレス変更画面
- [ ] パスワード変更画面
- [ ] スケジュール画面（メイン画面）
- [ ] スケジュール管理画面
- [ ] To Do（管理）画面
- [ ] マイページ画面
- [ ] プロフィール画面
- [ ] 学習時間記録画面
- [ ] ゲーミフィケーション管理画面（プロフィール画面に統合も要検討）
- [ ] 記事作成・投稿画面
- [ ] 利用規約画面
- [ ] お問い合わせ画面
- [ ] プライバシー・ポリシー画面

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by uutan58** [comment]
ご指導ありがとうございます。

承知いたしました。
機能については開発中に適宜調整し、まずはMVPリリースをすることを最優先に稼働していきます。
